# spec/swagger/v1/swagger.yaml
openapi: 3.0.1
info:
  title: Restaurant API
  version: v1
paths:
  /api/v1/orders:
    post:
      summary: Create an order
      description: Place a new order with menu items
      tags:
        - Orders
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                order:
                  type: object
                  properties:
                    notes:
                      type: string
                order_items:
                  type: array
                  items:
                    type: object
                    properties:
                      menu_item_id:
                        type: integer
                      quantity:
                        type: integer
      responses:
        '201':
          description: Order created successfully
        '401':
          description: Unauthorized
        '422':
          description: Validation error
  
  /api/v1/reservations:
    post:
      summary: Create a reservation
      description: Make a table reservation
      tags:
        - Reservations
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                reservation:
                  type: object
                  properties:
                    table_number:
                      type: integer
                    reserved_at:
                      type: string
                      format: date-time
      responses:
        '201':
          description: Reservation created successfully
        '401':
          description: Unauthorized
        '422':
          description: Validation error

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key